### ISSUE TITLE
[FR] integration for home assistant

### ISSUE THREAD

**Issue by thundergreen** [bkbilly/asterisk_call_status#4]
Hello I find your project very nice neat and useful. But I'm using hassos which does not allow me to install packages.but with integration it would work. Are U interested in making an integration out of this ? Would be awesome ☺️

**Comment by bkbilly** [comment]
I am not sure how to create an app for HASSOS, but theoretically it could be installed on this OS because it's a Linux system.
I've never used it, so I don't know how to do this integration.

Maybe I could create a home assistant integration in the future so I will leave this feature request open.

**Comment by bkbilly** [comment]
This has been done.
