### ISSUE TITLE
There is no icon in "Service info"

### ISSUE THREAD

**Issue by DaN66O** [bkbilly/asterisk_call_status#5]
Thank you for your work. !!

There is no icon in "Service info"
![Screenshot_25](https://github.com/bkbilly/asterisk_call_status/assets/113509164/f4aac782-141e-4d42-8bb1-248a58d2cd93)

Link to a non-existing icon
https://brands.home-assistant.io/asterisk_call_status/icon.png

p.s. 
Two words "status" in the sensor are probably superfluous
sensor.asterisk_call_status_status

**Comment by bkbilly** [comment]
I haven't created an icon for this project yet so home assistant defaults to a non existing icon.
As for the status, I didn't know what to call it and this was the first thing that I thought. I don't think that I'll change it because it will break the automations that are already configured.

**Comment by DaN66O** [comment]
I took the liberty to draw an icon and a logo))
Suddenly like it)

logo.png
![icon](https://github.com/bkbilly/asterisk_call_status/assets/113509164/2f737256-963f-4b3b-8062-655d5e06a99b)
logo.png
![logo](https://github.com/bkbilly/asterisk_call_status/assets/113509164/a8c91f8d-ec69-4f47-9723-f13b3876a662)

**Comment by bkbilly** [comment]
That looks amazing, though you should remove the grid pattern to make it transparent.
You can create a PR at [Home Assistant Brands](https://github.com/home-assistant/brands) under the **custom_integrations** with the name **asterisk_call_status**.
If you are having trouble creating a PR, you can send them to me to make this PR.

**Comment by DaN66O** [comment]
English is not my native language. I think I will have problems with PR.
I'll post the files here with a transparent background
logo.png
![logo](https://github.com/bkbilly/asterisk_call_status/assets/113509164/dee9d8e9-928a-4239-9cf5-a6868fe15767)

logo@2x.png
![logo@2x](https://github.com/bkbilly/asterisk_call_status/assets/113509164/5e6d1627-5e78-413d-b854-baa45e0c5376)

icon.png
![icon](https://github.com/bkbilly/asterisk_call_status/assets/113509164/3085633b-a53f-428b-8250-338a77716bcd)

icon@2x.png
![icon@2x](https://github.com/bkbilly/asterisk_call_status/assets/113509164/08a5840f-f4ce-4e8f-881f-ff186bd77fea)

**Comment by DaN66O** [comment]
[image: logo.png][image: ***@***.***[image: icon.png][image: ***@***.***

сб, 22 июл. 2023 г. в 11:58, Vasilis Koulis ***@***.***>:

**Comment by bkbilly** [comment]
I've created a PR. You can see it's progress here: https://github.com/home-assistant/brands/pull/4559
Thank you for taking an interest on creating images for my project!

**Comment by DaN66O** [comment]
Did I understand correctly that you can't use the asterisk icon in your icons ?

**Comment by bkbilly** [comment]
That's right. 
Unfortunately you can't create custom icons using official logos.
Most likely this has to do with licensing issues.

**Comment by DaN66O** [comment]
I didn't know that.
I should have done so then

![icon2](https://github.com/bkbilly/asterisk_call_status/assets/113509164/62ddc220-7bc1-4151-add3-7a747dec552e)

**Comment by bkbilly** [comment]
I've created a new PR with the new icons you sent me.
You can see it's progress here: https://github.com/home-assistant/brands/pull/4560
