### ISSUE TITLE
After updating home assistant to version 2023.8.1 asterisk_call_status stopped working.

### ISSUE THREAD

**Issue by DaN66O** [bkbilly/asterisk_call_status#8]
asterisk_call_status stopped working. 
The logs are empty.
![Screenshot_24](https://github.com/bkbilly/asterisk_call_status/assets/113509164/1d9974a4-2b7f-4212-86dd-2d46d08d02b1)

**Comment by bkbilly** [comment]
Fixed this on the latest release
